### ISSUE TITLE
NoMethodError in add_newsletter

### ISSUE THREAD

**Issue by shawndrost** [bmuller/gatling_gun#1]
Howdy,

Running into a problem with my first attempt to do anything.  The backtrace is somewhat opaque -- any ideas?

https://gist.github.com/1277443

Thanks!
-Shawn

ps -- ideally, lib/gatling_gun/api_call.rb wouldn't rescue all errors, just the ones that it needed to.

**Comment by JEG2** [comment]
Interesting, it looks like ActiveSupport has patched Rails in a way that breaks parameter encoding for whatever you are passing.  Any chance you could share the call you are making in mailchimp_controller.rb line 13?

I agree with the error rescuing problem.  Unfortunately, Net::HTTP can throw a metric ton of unrelated errors.  That makes it hard to catch them all.

**Comment by shawndrost** [comment]
Hey James,

I found the problem -- not a bug!

Re: Net::HTTP exceptions: I dug up a blog post I remember reading on that
topic...

http://tammersaleh.com/posts/rescuing-net-http-exceptions

Here's what happened, if you're interested:

```
body = render_to_string("newsletters/bigimage", layout: false)
```

...doesn't output a string!  Incredibly, appending ".to_s" doesn't either.
 String.new(...) worked.

**Comment by JEG2** [comment]
Thanks for the link.  I've incorporated this into the new 0.0.3 gem.
