### ISSUE TITLE
delete_list on non existing list returns success

### ISSUE THREAD

**Issue by thbar** [bmuller/gatling_gun#4]
SendGrid seems to return both HTTP 200 and an error as data in that case:

``` ruby
#<GatlingGun::Response:0x7fe6e94d68e0
  @data = {
    "error" => "List does not exist"
  },
  @success = true,
  attr_reader :http_response_code = "200"
>
```

Do we want success to be set to false in that case?

If you wonder, I started looking at this because I thought about adding bang equivalents to each method (like delete_list! would raise an exception unless we have a success).

**Comment by JEG2** [comment]
Hmm, I could go either way on this one.  It is kind of a success if you think of it as, "Make sure this list doesn't exist."  OK, it doesn't.  On the downside, it doesn't allow you to know if it did exist.  Tough call.  It just doesn't really feel like an error case to me though.

Just FYI, I purposefully built gatling_gun not to throw exceptions.  Getting an error response from an API shouldn't potentially halt my program, in my opinion.  It's a failure, not really an error.  I might be OK with other methods for that, but I definitely don't want it to be the default behavior.

**Comment by thbar** [comment]
On your first note: I do agree - tough call! As a user, it's a bit surprising at first. As a gem implementor, I'm not sure what do to.

On the exceptions: I totally meant to add new bang ! methods and not change the default (which I do respect :-). In my case I will always wrap calls to verify and raise, as I prefer to get a notification and stop the processing early on.

FWIW and in case it helps someone else, here's my quick first stab at a "fail-fast" wrapper:

``` ruby
def sg!
  result = yield
  raise "Failure: #{result['error']}" unless result.success?
  raise "Failure on data! - Error is #{result['error']}" if result['error']
  result
end
```

I would probably just wrap all the existing methods with a bang equivalent that would achieve the same logic.

**Comment by JEG2** [comment]
Feel free to make a pull request or two.  We can discuss more there.
