### ISSUE TITLE
Unsubscribe tag from the "Unsbscription" app on sedngrid does not seem work

### ISSUE THREAD

**Issue by hghia** [bmuller/gatling_gun#7]
Hi,

I am using the newsletter API want to include a unsbscribe link at the end of my email. FOr doing that you can enable and set up the "Subscription Tracking" app to look for a particular tag in the newsletter text for eg: [UNSUBSCRIBE] and then this tag will be replaced with the unsubscribe link.  It works when I create a newsletter from sendgrid.com UI but does not seem to work when I add the tag using the newsletter api.

For eg:
SendGrid.add_newsletter( newsletter_name,
                             identity: IDENTITY,
                             subject:  newsletter.title,
                             html:     "<h1>#{newsletter.content}</h1> [unsubscribe]" )
Please advice.

Thanks,
HItesh

**Comment by JEG2** [comment]
I have use the replacements in newsletters before.  Sendgrid use to have some issues here, but I think they were solved last I checked.  My advice is to call their support line.  That's how I was able to troubleshoot similar issues in the past.  They seem to be pretty helpful about this kind of thing, in my experience.  Hope that helps.
